### ISSUE TITLE
Support generating mock for interfaces with generics

### ISSUE THREAD

**Issue by pavleprica** [uber-go/mock#128]
Hey team,

Hope you are doing well. 
Stumbled upon on [this](https://github.com/golang/mock/issues/621) issue. In code as well as on the archived repo.
To not copy paste too much, is this perhaps on the roadmap for you?

It seems that the previous team was on it, but didn't got to the latest release including it.

**Comment by tulzke** [comment]
Hi @pavleprica .
This has already been implemented and is working.

### Example from a real project:
#### Interface:
```go
type Storage[V any] interface {
	Set(ctx context.Context, item V, rowVersion internal.RowVersion) error
	Delete(ctx context.Context, item V, rowVersion internal.RowVersion) error
}
```
#### Mock:
```go
...
// MockStorage is a mock of Storage interface.
type MockStorage[V any] struct {
	ctrl     *gomock.Controller
	recorder *MockStorageMockRecorder[V]
}
...
// Set mocks base method.
func (m *MockStorage[V]) Set(ctx context.Context, item V, rowVersion internal.RowVersion) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", ctx, item, rowVersion)
	ret0, _ := ret[0].(error)
	return ret0
}
...
```

**Comment by pavleprica** [comment]
Hey @tulzke,
Thank you for your response!

But this doesn't seem like handling of generics by `gomock`? Perhaps I'm just not seeing the whole picture.

But this is a "custom" implementation of the interface to mock it "manually". Not like you can rely on the `.EXPECT()` methods.

Or the example you provided is from the generated code?

**Comment by krak3n** [comment]
I'm coming across a similar problem I think, I'm trying to create a mock for this interface (a connectrpc handler interface generated from protos):

```go
type ServiceHandler interface {
	Set(context.Context, *connect.Request[package.SetRequest]) (*connect.Response[package.SetResponse], error)
}
```

`mockgen` errors with:

```
2023/12/18 11:58:16 Failed to format generated source code: cachetest/handler.go:40:84: missing ',' in type argument list (and 5 more errors)
```

The generated code included with the error:

```
// Code generated by MockGen. DO NOT EDIT.
// Source: REDACTED
//
// Generated by this command:
//    mockgen githib.com/repo/path/package/packageconnect ServiceHandler
// Package cachetest is a generated GoMock package.
package cachetest

import (
        reflect "reflect"
        connect "connectrpc.com/connect"
        context "context"
        gomock "go.uber.org/mock/gomock"
)

// MockHandler is a mock of Handler interface.
type MockHandler struct {
        ctrl     *gomock.Controller
        recorder *MockHandlerMockRecorder
}

// MockHandlerMockRecorder is the mock recorder for MockHandler.
type MockHandlerMockRecorder struct {
        mock *MockHandler
}

// NewMockHandler creates a new mock instance.
func NewMockHandler(ctrl *gomock.Controller) *MockHandler {
        mock := &MockHandler{ctrl: ctrl}
        mock.recorder = &MockHandlerMockRecorder{mock}
        return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHandler) EXPECT() *MockHandlerMockRecorder {
        return m.recorder
}

// Set mocks base method.
func (m *MockHandler) Set(arg0 context.Context, arg1 *connect.Request[githib.com/repo/path/package.SetRequest]) (*connect.Response[githib.com/repo/path/package.SetResponse], error) {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "Set", arg0, arg1)
        ret0, _ := ret[0].(*connect.Response[githib.com/repo/path/package.SetResponse])
        ret1, _ := ret[1].(error)
        return ret0, ret1
}

// Set indicates an expected call of Set.
func (mr *MockHandlerMockRecorder) Set(arg0, arg1 any) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockHandler)(nil).Set), arg0, arg1)
}
```

As you can see from the generated code it doesn't look like `mockgen` can resolve the generic type imports correctly and we get invalid code.

**Comment by MartinForReal** [comment]
It is because generics are not supported in reflect mode https://github.com/uber-go/mock/blob/main/mockgen/model/model.go#L421

**Comment by pavleprica** [comment]
Hey there @tra4less,

I generally replicated the issue from the archived repository. 
I ran into it, while running into my own problem, which I presume might be related to the one.

But, to replicate my issue, you can use [this](https://play.golang.com/p/FVk1Wr1g7cg) code.
A bit simplified, but should do the trick

**Comment by itsNotMyUsername** [comment]
> Hey there @tra4less,
> 
> I generally replicated the issue from the archived repository. I ran into it, while running into my own problem, which I presume might be related to the one.
> 
> But, to replicate my issue, you can use [this](https://play.golang.com/p/FVk1Wr1g7cg) code. A bit simplified, but should do the trick

exactly same issue here

**Comment by ahmetb** [comment]
Seeing exactly the same issue. In my case, the generated code has full package/module paths in the generics qualifiers:

```go
// Code generated by MockGen. DO NOT EDIT.
// Source: golang.linkedin.com/config-publish-api/config-publish-api-go/generated/com/linkedin/config/compiledConfigDescriptors (interfaces: Client)
...

func (m *MockClient) Create(arg0 *config.CompiledConfigDescriptor) (*common.CreatedEntity[*golang.linkedin.com/config-publish-api/config-publish-api-go/generated/com/linkedin/config/compiledConfigDescriptors.CompiledConfigDescriptors_ComplexKey], error) {

...

func (m *MockClient) CreateWithContext(arg0 context.Context, arg1 *config.CompiledConfigDescriptor) (*common.CreatedEntity[*golang.linkedin.com/config-publish-api/config-publish-api-go/generated/com/linkedin/config/compiledConfigDescriptors.CompiledConfigDescriptors_ComplexKey], error) {
```

which looks like obvious syntax errors.

**Comment by tkrause** [comment]
Seeing the same thing

**Comment by appxpy** [comment]
Same thing, syntax error on generating mocks for interfaces with embedded generics.

**Comment by jonnylangefeld** [comment]
My issues were the same as described by @krak3n and @ahmetb. I'm using connectrpc and saw the full module names in the generated code, creating the syntax errors.

But @tra4less's solution of using `mockgen` source mode worked for me. I ran this command:
```bash
mockgen \
  -source=./pkg/proto/life/v1/lifev1connect/life.connect.go \
  -destination=./pkg/subsystem/mocks/mock_subsystem_service.go \
  -package=mocks github.com/jonnylangefeld/life/pkg/proto/life/v1/lifev1connect \
  SubsystemServiceClient
```

The generated code now had an import like this:
```go
lifev1 "github.com/jonnylangefeld/life/pkg/proto/life/v1"
```

And the endpoints correctly used the named import in the generics code:
```go
// SayHello mocks base method.
func (m *MockHelloServiceClient) SayHello(arg0 context.Context, arg1 *connect.Request[lifev1.SayHelloRequest]) (*connect.Response[lifev1.SayHelloResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SayHello", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[lifev1.SayHelloResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}
```

**Comment by lrascao** [comment]
Also ran into this issue in which `mockgen` source mode doesn't help, here's a slim repro: https://play.golang.com/p/VPmHL06LTPH

generated code is:
```
// Set mocks base method.
func (m *MockSample) Set(arg0 context.Context, arg1 serializable) error {
```

when it should be:
```
// Set mocks base method.
func (m *MockSample) Set(arg0 context.Context, arg1 serializable[any]) error {
```
