### ISSUE TITLE
Build constraints in generated files

### ISSUE THREAD

**Issue by ARR4N** [uber-go/mock#190]
*Requested feature* The ability to specify build constraints to be added with `//go:build <constraints>` in the generated files.

*Why the feature is needed* Generated mocks are intended for testing but are regularly in non `_test.go` files to allow for cross-package imports. This risks the leakage of test-only code into production, which can easily be prevented with build constraints ([example](https://github.com/ava-labs/avalanchego/pull/3173)).

*(Optional) Proposed solution* #191

**Comment by jaceee** [comment]
+1
I really need this. Thanks for the PR too, that's exactly what I need.

**Comment by Gris87** [comment]
+1
We need it too
