### ISSUE TITLE
Proposal to resolve Issue #116 without generating ISGOMOCK Method in structs

### ISSUE THREAD

**Issue by eyasy1217** [uber-go/mock#193]
*Requested feature*
I want to resolve https://github.com/uber-go/mock/issues/116 without generating ISGOMOCK method.
ISGOMOCK method was implemented by https://github.com/uber-go/mock/pull/144.

*Why the feature is needed*
I think it is disturbing that the ISGOMOCK method for testing is generated in every struct.

*(Optional) Proposed solution*
Do you have any good ideas?

**Comment by JacobOaks** [comment]
Hey @eyasy1217 - we agree that we should come up w/ a better way to do this. One way we could do it is through reflect instead of generating `ISGOMOCK()`.

If we do want to make this change, we should make it a release-blocker as well.

**Comment by JacobOaks** [comment]
Fixed by #204. Thanks.
