### ISSUE TITLE
MacOS install failure

### ISSUE THREAD

**Issue by bap2pecs** [uber-go/mock#211]
**Actual behavior** 

see "[1]    21992 killed     mockgen -v"

**Expected behavior**

see version

**To Reproduce** Steps to reproduce the behavior

```
rm $(which mockgen)
go install go.uber.org/mock/mockgen@latest
mockgen -v
```

**Additional Information**

-   gomock mode (reflect or source):
-   gomock version or git ref:
-   golang version: go version go1.22.4 darwin/arm64

**Triage Notes for the Maintainers**
```
ls -l ~/Library/Logs/DiagnosticReports/mockgen*
```
found `/Users/<username>/Library/Logs/DiagnosticReports/mockgen-2024-10-14-115539.ips`

content: https://gist.github.com/bap2pecs/ac72e34c649dc9f64f4f79c58e9dec6c

additional context: it used to work. iirc I noticed this issue about 2 week ago

**Comment by tturbs** [comment]
@bap2pecs 
Check this out
https://github.com/uber-go/mock/issues/185#issuecomment-2389654499

**Comment by bap2pecs** [comment]
https://github.com/uber-go/mock/issues/185#issuecomment-2414337468
