### ISSUE TITLE
Add helpful info to README regarding GOPATH during installation

### ISSUE THREAD

**Issue by carson-brill** [uber-go/mock#65]
*Requested feature* 
- I'd like to add a helpful tidbit about ensuring GOPATH/bin is part of PATH, as this held me up for a bit when trying to use this tool.

*Why the feature is needed* 
- Will allow more users to start using the tool faster

*(Optional) Proposed solution*  
- I don't have push access, but adding a few lines after line 27 in the Installation section would suffice:

To ensure it was installed correctly, use:
```
mockgen -version
```

If not, make sure your GOPATH/bin is in your PATH. Otherwise add it with:
```
export PATH=$PATH:$(go env GOPATH)/bin
```

**Comment by carson-brill** [comment]
@r-hang ah thank you for clarifying! Opened up the PR now.

**Comment by kahakai** [comment]
Probably time to close the issue after the PR https://github.com/uber-go/mock/pull/139 is merged.
